config/routes.rb
Eleven::Application.routes.draw do
  get "users/user_params"
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about" # creates about path
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base

	belongs_to :user

	has_attached_file :image, :styles => { :medium => "400x400>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  validates :image, presence: true
  validates :title, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  has_attached_file :profile_image, :styles => { :medium => "400x400>", :thumb => "100x100>" }

  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  	def configure_permitted_parameters
    	devise_parameter_sanitizer.for(:sign_up) << :name
    	devise_parameter_sanitizer.for(:account_update) << :name
    	devise_parameter_sanitizer.for(:account_update) << :profile_image
  	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)

  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.' 
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit the pin." if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def body_class
    [controller_name, action_name].join('-')
  end

  def is_path?(*paths)
  paths.include?(request.path)
	end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/headers/_index.html.erb
	<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
		  <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header">
        <ul class="nav navbar-nav pull-left">
          <li>
          	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Menu">
          		<span class="sr-only">Toggle navigation</span>
          	  <span class="fa fa-bars"></span>	              	
          	</a>
          </li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <li>
          	<%= link_to new_pin_path, method: :get, class: "new-tone", title: "New" do %>
						 		<span class="fa fa-plus"></span> 
						<% end %>
          </li>
        </ul>    
		    <%= link_to root_path, class: "navbar-brand" do %>
		    	<!--<img src="/assets/Eleven-Logo2.svg" alt="Eleven" title="Eleven">-->
		    	<%= image_tag "Eleven-Logo2.svg" %>
		    <% end %>
		  </div>

		  <!-- Collect the nav links, forms, and other content for toggling -->
		  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		    <ul class="nav navbar-nav navbar-right">
		      <li>
		      	<%= link_to root_path do%>
		      		<span class="fa fa-home fa-fw icon-lg"></span> 
		      		<span class="text">Home</span>
						<% end %>
		      </li>	      
		      <li>
		      	<%= link_to root_path do%>
		      		<i class="fa fa-search fa-fw icon-lg"></i> Discover
						<% end %>
		      </li>
		      <% if user_signed_in? %>
		      	<li>
		      		<%= link_to root_path do%>
		      			<i class="fa fa-book fa-fw icon-lg"></i> Library
							<% end %>
		      	</li>
		      	<li>
		      		<%= link_to edit_user_registration_path do %>		      		
		      			<i class="fa fa-user fa-fw icon-lg"></i> Profile							
							<% end %>
		      	</li>
		      	<!--<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>-->
		      <% else %>
		      	<li>
		      		<%= link_to new_user_session_path do %>		      			
		      			<i class="fa fa-arrow-right fa-fw icon-md"></i> Sign In
		      		<% end %>
		      	</li>
		      <% end %>
		    </ul>
		  </div><!-- /.navbar-collapse -->
		</div>
	</nav>

app/views/headers/_signin.html.erb
	<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
		  <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header">        
        <ul class="nav navbar-nav pull-left">
          <li>
          	<%= link_to root_path, method: :get, class: "new-tone", title: "New" do %>
						 		<span class="fa fa-arrow-left"></span> 
						<% end %>
          </li>
        </ul>    
		    <h1 class="navbar-brand">Sign In</h1>
		  </div>

		</div>
	</nav>

app/views/headers/_signup.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">        
      <ul class="nav navbar-nav pull-left">
        <li>
        	<%= link_to root_path, method: :get, class: "new-tone", title: "New" do %>
					 		<span class="fa fa-arrow-left"></span> 
					<% end %>
        </li>
      </ul>    
	    <h1 class="navbar-brand">Sign Up</h1>
	  </div>

	</div>
</nav>

app/views/layouts/_header.html.erb
	<%= render 'headers/index' if user_signed_in? %>

	<%= render 'headers/signin' if is_path?("/users/sign_in") %>

	<%= render 'headers/signup' if is_path?("/users/sign_up") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eleven</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">

	<%= render 'layouts/header' %>

	<% if current_page?(root_path) %>
		<%= render "pages/home" unless user_signed_in? %>
	<% end %>

	<div class="main-container container">		
		<!-- alert message -->
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
			
		<!-- main content -->		
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<!-- Landing Page -->

<div class="index-wrap pull-top container text-center">	
	
	<div class="wrap-fixed">
		<div class="home-logo text-center col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
			<img src="<%= asset_path "Eleven-Logo2.svg" %>" class="home-logo-img" alt="Eleven" title="Eleven">
		</div>
		<div class="text-center col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
			<p class="home-tagline lead text-center">Create & Discover Amazing Tone</p>
		</div>
	</div>


	<div id="footer-fixed">
		<div class="home-buttons col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4">
	    <%= link_to "Sign In", new_user_session_path, class: "btn btn-default btn-block btn-lg" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-block btn-lg" %>
		</div>
  </div>
</div>	

app/views/pages/about.html 2.erb
<div class="container col-md-4 col-md-offset-4">
	<h1>About Us</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id rutrum nunc, eu dignissim nibh. Etiam ullamcorper massa purus, ut pellentesque sem sollicitudin a. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur venenatis orci sit amet nisl facilisis, ut tincidunt mauris fermentum. Pellentesque ornare.</p>
		<br />
		<div>
			<div class="btn-group">
			  <button type="button" href="<%=  %>" class="btn btn-primary btn-lg">Sign Up</button>
			  <button type="button" href="<%=  %>" class="btn btn-default btn-lg">Sign In</button>
			</div>
		</div>
		<br />
	<hr />
</div>

app/views/pages/about.html.erb
<div class="container col-md-4 col-md-offset-4">
	<h1>About Us</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id rutrum nunc, eu dignissim nibh. Etiam ullamcorper massa purus, ut pellentesque sem sollicitudin a. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur venenatis orci sit amet nisl facilisis, ut tincidunt mauris fermentum. Pellentesque ornare.</p>
		<br />
		<div>
			<div class="btn-group">
			  <button type="button" href="<%=  %>" class="btn btn-primary btn-lg">Sign Up</button>
			  <button type="button" href="<%=  %>" class="btn btn-default btn-lg">Sign In</button>
			</div>
		</div>
		<br />
	<hr />
</div>

app/views/pages/index.html.erb
<div class="container col-md-4 col-md-offset-4">

	<h1>Index</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id rutrum nunc, eu dignissim nibh. Etiam ullamcorper massa purus, ut pellentesque sem sollicitudin a. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur venenatis orci sit amet nisl facilisis, ut tincidunt mauris fermentum. Pellentesque ornare.</p>
		<br />
		<div>
			<div class="btn-group">
				<%= link_to "Sign In", new_user_session_path, class: "btn btn-default btn-lg" %>
				<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
			</div>
		</div>
		<br />
	<hr />
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<% if user_signed_in? %>
  <!--<h1 class="text-center">All Tones</h1>-->

  <div class="row">
    <div id="pins" class="">
      
      <% @pins.each do |pin| %>

        <div class="box">       

          <div>  
            <!-- Tone Settings Dropdown -->
            <% if pin.user == current_user %>
              <div class="actions btn-group">                        
                <button type="button" class="btn btn-dark dropdown-toggle btn-square" data-toggle="dropdown">
                  <i class="fa fa-cog icon-md"></i>                
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to edit_pin_path(pin), class: "" do %>
                      <i class="fa fa-pencil icon-md"></i> Edit
                    <% end %>
                  </li>
                  <li>
                    <%= link_to pin, class: "", method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="fa fa-times icon-md"></i> Delete
                    <% end %>
                  </li>
                </ul>         
              </div>
            <% end %>      
            
            <!-- Image -->
            <%= link_to pin, class: "play-box" do %>               
              <div class="play-button"></div>
              <div class="image" style="background-image: url('<%= pin.image.url(:medium) %>;')"></div>
            <% end %>  
          </div> 
          
          <%= link_to pin, class: "btn btn-primary btn-lg btn-block btn-bottom tone-title not-round" do %>
            <% if pin.title == nil %>
              Untitled
            <% else %>
              <%= truncate(pin.title, :length => 28) -%>            
            <% end %>
            <i class="fa fa-arrow-right icon-md pull-right"></i>
          <% end %>
          
          <div class="container">
            <div class="user-section">
              <%= link_to pin do %>              
                <%= image_tag pin.user.profile_image.url(:thumb), class: "user-thumb img-circle", alt: "" %>
                <strong><%= pin.user.name if pin.user %></strong>
              <% end %>
              <span class="pull-right time-ago text-muted">
                <i class="fa fa-clock-o"></i> <%= time_ago_in_words(pin.updated_at) %>
              </span>        
            </div>

            <div class="box-section retones">
              <a><strong>33 retones</strong></a>
            </div>

            <div class="box-section likes">
              <a><strong>26 people like this</strong></a>
            </div>

            <div class="box-section comments">
              <p>
                <a><strong>David Riddle</strong></a> I'm going to use this sound.
              </p>
              <p>
                <a><strong>Nick Groesch</strong></a> Bring up the gain a notch or two and bring down the tone dial on your guitar and this one is money!
              </p>
            </div>
          </div>

          <div class="text-center options">          
            <ul class="nav nav-justified">
              <li><a href="#"><span class="fa fa-plus icon-lg"></span></a></li>            
              <li><a href="#"><span class="fa fa-smile-o icon-lg"></span></a></li>
              <li><a href="#"><span class="fa fa-comment icon-lg"></span></a></li>
              <li><a href="#"><span class="fa fa-share icon-lg"></span></a></li>
              <li><a href="#"><span class="fa fa-ellipsis-h icon-lg"></span></a></li>                             
            </ul>                                  
          </div>  
        </div>
      <% end %> 
    </div>
  </div>

  <div class="text-center">
     <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
  </div>


  <!--<div class="row text-center">
    <ul class="pagination">
      <% if @pins.previous_page %>
        <li><%= link_to "< ", params.merge(:page => @pins.previous_page ) %></li>
      <% end %>
      <li>Page <%= @pins.current_page %> of <%= @pins.total_pages %></li>
      <% if @pins.next_page %>
        <li><%= link_to ">", params.merge(:page => @pins.next_page ) %></li>
      <% end %>
    </ul>
  </div>-->

<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading text-center">
				<%= image_tag @pin.image.url(:medium) %>
			</div>
			<div class="panel-body">
				<p>
					<%= link_to @pin do %>            
	          <%= image_tag @pin.user.profile_image.url(:thumb), class: "user-thumb img-circle", alt: "" %>
	          <strong><%= @pin.user.name if @pin.user %></strong>
	        <% end %>
					<span class="pull-right time-ago text-muted">
	          <i class="fa fa-clock-o"></i> 
	          <%= time_ago_in_words(@pin.updated_at) %>
	        </span> 
        </p> 

				<p><%= @pin.title %></p>
				<% if @pin.user == current_user %>				
					<%= link_to edit_pin_path(@pin) do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit
           <% end %>
				<% end %>
			</div>
		</div>
	</div>
<div>

app/views/users/user_params.html.erb
<h1>Users#user_params</h1>
<p>Find me in app/views/users/user_params.html.erb</p>